### ISSUE TITLE
PasswordAuthenticationMiddleware takes an excessive amount of time to complete requests

### ISSUE THREAD

**Issue by bsrz** [vapor/bcrypt#5]
I have this sample project:
https://github.com/bsarrazin/server-SkunkTrail

If you put a breakpoint in `RegistrationController.swift:15` and perform this cURL request...
```
## Register
curl -X "POST" "http://0.0.0.0:8080/api/v1/register" \
     -H "Content-Type: application/json" \
     -d $'{
  "email": "c422b4fe-599a-4387-a305-caccbfdda8ca@7swift.io",
  "password": "password",
  "last_name": "Ren",
  "first_name": "Kylo"
}'
``` 
... you will see it takes an excessive amount of time to complete (~6sec on my 2017 MBP).
The same thing happens when you put a breakpoint in `LoginController.swift:7` and perform this cURL request (after performing the first one to create the user):
```
## Login
curl -X "POST" "http://0.0.0.0:8080/api/v1/login" \
     -H "Content-Type: application/json" \
     -u 2c92283c-dbcc-4531-912b-6cd2488498ee@7swift.io:password \
     -d $'{}'
```

You can following the conversation I've had in the Vapor slack workspace:
https://qutheory.slack.com/archives/C0N6LGM0W/p1508611521000015

**Comment by tanner0101** [comment]
i'm guessing this is a problem w/ password hashing being slow. 
- which swift version are you using?
- are you using bcrypt? 
- if so, what's your cost factor. 
- does the time it takes change in if built in release mode?

**Comment by Joannis** [comment]
@tanner0101 Swift 4.0, BCrypt, cost factor 4 or 12 from slack and the code example.

This bug has been investigated by me and seems to be a compiler issue in Swift 4's debug compilation. Specifically the `encipher` function. Running this on Release should fix all issues.

<img width="1024" alt="screen shot 2017-10-26 at 00 18 39" src="https://user-images.githubusercontent.com/1951674/32026140-43d030b2-b9e3-11e7-8875-af08e15c9215.png">

EDIT: My recommended (temporary) solution is running a different cost factor on debug mode (locally). Your live server should be compiled on release, regardless. So the performance should be good there

**Comment by tanner0101** [comment]
Oops, sorry. Missed that code was supplied. @bsarrazin can you verify if compiling release solves the problem? If so, I'd also recommend using a lower cost factor in development mode. That way you can continue to compile debug without having slow hashing.

This can be easily done by adding a `Config/development/bcrypt.json` file with the lower cost factor. 

Or conversely by adding a `Config/production/bcrypt.json` with the higher cost factor and having the default `Config/bcrypt.json` contain a lower one. 

Additionally, you might consider using password auth for just login/signup and creating a token to verify subsequent requests. This is a lot more performant than hashing the password each request.

**Comment by bsrz** [comment]
This is super old, unlikely to be still applicable, we can reopen if needed.
