### ISSUE TITLE
Unidentified developer after adding BCrypt framework to project

### ISSUE THREAD

**Issue by rohithjnayak** [vapor/bcrypt#8]
Hello,
           I downloaded BCrypt from github, fetched package using SPM, created xocde project out of it using **swift package generate-xcodeproj** command. But when I integrate this framework into our project, I get unidentified developer alert from gatekeeper. I set code signing to Mac Developer for BCrypt framework as well, but it didn't help. I am using Xcode 10 and Swift 4.2. Is there is any solution or workaround for code signing issue?

**Comment by 0xTim** [comment]
Closing due to age - this should be resolved in SwiftPM now
